#!/usr/bin/env bash
container="apache"
if [ "$2" != "" ]
then
    container=$2
fi

docker-compose exec --user www-data "$container" npm i grunt
docker-compose exec --user www-data "$container" npm i
./magento "$container" deploy:mode:set developer
